### ISSUE TITLE
distribution is incorrectly configured as a uriorcurie

### ISSUE THREAD

**Issue by RobNicholsGDS** [co-cddo/ukgov-metadata-exchange-model#72]
**Describe the bug**
When validating a distribution element, the system is only excepting a string as valid input

** The error **
The definition at https://github.com/co-cddo/ukgov-metadata-exchange-model/blob/main/src/model/uk_cross_government_metadata_exchange_model.yaml#L317 is incorrect.

In the section:
```yaml
  distribution:
    slot_uri: dcat:distribution
    description: An available distribution of the dataset.
    recommended: true
    multivalued: true
    range: uriorcurie
```
The range should be `distribution` and not `uriorcurie`.
